# Generated by Django 3.2 on 2023-04-24 20:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[('dia_1', 'Dia 1'), ('dia_2', 'Dia 2')])),
                ('hora', models.DateTimeField()),
                ('actividad', models.CharField(max_length=254)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('fotografia_actividad', models.ImageField(upload_to='', verbose_name='Imagen relacionada')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hotel', models.CharField(max_length=254)),
                ('direccion', models.FileField(upload_to='')),
                ('imagen_hotel', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, unique=True)),
                ('telefono', models.IntegerField(max_length=13, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('area_estudios', models.TextField(verbose_name='Area de estudios')),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('curriculum', models.FileField(upload_to='')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creacion')),
                ('fotografia_instructor', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
