# Generated by Django 3.2 on 2023-04-24 21:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20230424_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='dia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='direccion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
