# Generated by Django 3.2 on 2023-04-25 15:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20230424_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=254)),
                ('lugar_evento', models.CharField(max_length=254)),
                ('descripcion_evento', ckeditor.fields.RichTextField()),
                ('map_evento', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=30)),
                ('url_seccion', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_patrocinador', models.CharField(max_length=254)),
                ('logo_patrocinador', models.ImageField(upload_to='', verbose_name='Logo Patrocinador')),
                ('url_patrocinadores', models.URLField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='nombre',
            new_name='nombre_instructor',
        ),
    ]
