# Generated by Django 3.2 on 2023-04-25 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_map_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronograma',
            options={'verbose_name': 'Cronograma', 'verbose_name_plural': 'Cronogramas'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Headers'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructores'},
        ),
        migrations.AlterModelOptions(
            name='patrocinadores',
            options={'verbose_name': 'Patrocinador', 'verbose_name_plural': 'Patrocinadores'},
        ),
        migrations.RenameField(
            model_name='cronograma',
            old_name='fotografia_actividad',
            new_name='fotografia',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='descripcion_evento',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='lugar_evento',
            new_name='lugar',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='map_evento',
            new_name='mapa',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='nombre_evento',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='imagen_hotel',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='nombre_hotel',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='fotografia_instructor',
            new_name='fotografia',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='nombre_instructor',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='patrocinadores',
            old_name='logo_patrocinador',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='patrocinadores',
            old_name='nombre_patrocinador',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='patrocinadores',
            old_name='url_patrocinadores',
            new_name='url',
        ),
        migrations.AddField(
            model_name='evento',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='eventos', verbose_name='Logo_evento'),
            preserve_default=False,
        ),
    ]
