# Generated by Django 3.2 on 2023-04-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20230425_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='fotografia',
            field=models.ImageField(upload_to='cronograma', verbose_name='Imagen relacionada'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='fotografia',
            field=models.ImageField(null=True, upload_to='instructor'),
        ),
        migrations.AlterField(
            model_name='patrocinadores',
            name='logo',
            field=models.ImageField(upload_to='patrocinadores', verbose_name='Logo Patrocinador'),
        ),
    ]
