# Generated by Django 3.2 on 2023-04-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20230425_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='cronogramas', verbose_name='Imagen relacionada'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='eventos', verbose_name='Logo_evento'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='hoteles'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='instructores'),
        ),
        migrations.AlterField(
            model_name='patrocinadores',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='patrocinadores', verbose_name='Logo Patrocinador'),
        ),
    ]
