# Generated by Django 3.2 on 2023-05-11 19:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20230425_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('objetivo', ckeditor.fields.RichTextField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.instructor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
