# Generated by Django 3.2 on 2023-05-11 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='url',
            field=models.URLField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
