# Generated by Django 3.2 on 2023-05-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_hotel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='seccion_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='url_seccion',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='fotografia',
            field=models.ImageField(blank=True, default='instructores/perfil.jpg', null=True, upload_to='instructores'),
        ),
    ]
