# Generated by Django 3.2 on 2023-05-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_auto_20230517_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='hora',
            field=models.TimeField(),
        ),
    ]
