# Generated by Django 3.2 on 2023-05-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_alter_cronograma_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='mapa',
            field=models.URLField(),
        ),
    ]
