# Generated by Django 3.2 on 2023-05-17 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_rename_descripcion_cronograma_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='hora2',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
