# Generated by Django 3.2 on 2023-05-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_cronograma_hora2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma_Dia2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('hora2', models.TimeField()),
                ('actividad', models.CharField(max_length=254)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='cronogramas', verbose_name='Imagen relacionada')),
            ],
            options={
                'verbose_name': 'Cronograma dia 2',
                'verbose_name_plural': 'Cronogramas dia 2',
            },
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='grupo',
        ),
    ]
