# Generated by Django 3.2 on 2023-05-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_auto_20230517_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
