# Generated by Django 3.2 on 2023-05-18 20:59

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0017_evento_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='hora2',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='hora_fin',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cronograma',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='mapa',
            field=ckeditor.fields.RichTextField(verbose_name='Mapa'),
        ),
    ]
