# Generated by Django 3.2 on 2023-05-19 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_auto_20230518_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='dia',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='area_estudios',
            field=models.CharField(max_length=254, verbose_name='Area de estudios'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='fotografia',
            field=models.ImageField(blank=True, default='instructores/perfil-default.jpg', null=True, upload_to='instructores'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
