# Generated by Django 3.2 on 2023-05-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_auto_20230519_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.DeleteModel(
            name='Cronograma_Dia2',
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='actividad',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.curso'),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='otra_actividad',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='tipo_actividad',
            field=models.CharField(choices=[('talleres', 'Talleres'), ('visitas_industriales', 'Visitas Industriales'), ('otro', 'Otro')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='dia',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.empresa'),
        ),
    ]
