# Generated by Django 3.2 on 2023-06-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_auto_20230526_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronograma',
            options={'ordering': ['hora_inicio'], 'verbose_name': 'Cronograma', 'verbose_name_plural': 'Cronogramas'},
        ),
        migrations.AlterField(
            model_name='instructor',
            name='fotografia',
            field=models.ImageField(blank=True, default='instructores/perfil-default.png', null=True, upload_to='instructores'),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=145)),
                ('apellido_paterno', models.CharField(blank=True, max_length=145, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=145, null=True)),
                ('email', models.EmailField(max_length=145)),
                ('tipo_participante', models.CharField(choices=[('estudiante_utyp', 'Estudiante UTyP'), ('docente_directivo_utyp', 'Docente - Directivo UTyP'), ('publico_general', 'Público General'), ('estudiantes_externos', 'Estudiantes Externos')], max_length=50)),
                ('universidad_empresa', models.CharField(max_length=145, verbose_name='Universidad o Empresa')),
                ('matricula', models.CharField(max_length=20, null=True)),
                ('numero_empleado', models.CharField(max_length=20, null=True)),
                ('inscrito', models.BooleanField(default=False)),
                ('referencia', models.CharField(blank=True, max_length=140, null=True)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='registro/comprobante')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.curso')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
