# Generated by Django 3.2 on 2023-05-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='foto',
            field=models.ImageField(default='default-640x480.png', help_text='El tamaño de la imagen debe ser de 640 x 480 pixeles', upload_to='registro'),
        ),
    ]
