# Generated by Django 3.2 on 2023-05-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_auto_20230526_1843'),
        ('eventos', '0023_alter_registro_foto'),
    ]

    operations = [
    ]
