# Generated by Django 3.2 on 2023-05-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0024_merge_20230531_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronograma',
            options={'ordering': ['hora_inicio'], 'verbose_name': 'Cronograma', 'verbose_name_plural': 'Cronogramas'},
        ),
        migrations.AlterField(
            model_name='instructor',
            name='fotografia',
            field=models.ImageField(blank=True, default='instructores/perfil-default.png', null=True, upload_to='instructores'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='registro/comprobante'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='foto',
            field=models.ImageField(blank=True, default='default-640x480.png', help_text='El tamaño de la imagen debe ser de 640 x 480 pixeles', null=True, upload_to='registro'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.curso'),
        ),
    ]
