# Generated by Django 3.2 on 2023-06-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0024_auto_20230622_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='aviso_privacidad',
            field=models.FileField(blank=True, null=True, upload_to='registro/aviso'),
        ),
        migrations.AddField(
            model_name='registro',
            name='formato_inscripcion',
            field=models.FileField(blank=True, null=True, upload_to='registro/inscripcion'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_participante',
            field=models.CharField(choices=[('estudiante_utyp', 'Estudiante UTYP'), ('docente_directivo_utyp', 'Docente - Directivo UTYP'), ('publico_general', 'Público General'), ('estudiantes_externos', 'Estudiantes Externos')], max_length=50),
        ),
    ]
