# Generated by Django 3.2 on 2023-06-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_auto_20230623_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='aviso_privacidad',
        ),
        migrations.AddField(
            model_name='registro',
            name='dia_taller',
            field=models.CharField(choices=[('jueves', 'Jueves'), ('viernes', 'Viernes')], default=1, max_length=20, verbose_name='Día taller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='dia_visita',
            field=models.CharField(choices=[('jueves', 'Jueves'), ('viernes', 'Viernes')], default=1, max_length=20, verbose_name='Día visita industrial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='visita_industrial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.empresa'),
        ),
    ]
