# Generated by Django 3.2 on 2023-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0026_auto_20230629_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='visita_industrial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registro',
            name='dia_taller',
            field=models.CharField(blank=True, choices=[('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=20, null=True, verbose_name='Día taller'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='dia_visita',
            field=models.CharField(blank=True, choices=[('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=20, null=True, verbose_name='Día visita industrial'),
        ),
    ]
