# Generated by Django 3.2 on 2023-07-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_auto_20230629_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='fotografia',
            field=models.ImageField(blank=True, default='perfil-default.png', null=True, upload_to='instructores'),
        ),
        migrations.AlterField(
            model_name='patrocinadores',
            name='url',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
    ]
