# Generated by Django 3.2 on 2023-06-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0030_alter_registro_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='comprobante_pago',
            field=models.FileField(default='default-640x480.png', upload_to='registro/comprobante'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='foto',
            field=models.ImageField(default='default-640x480.png', help_text='El tamaño de la imagen debe ser de 640 x 480 pixeles', upload_to='registro'),
        ),
    ]
