# Generated by Django 3.2 on 2023-06-13 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_remove_registro_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.curso'),
        ),
    ]
