# Generated by Django 3.2 on 2023-03-16 19:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('becas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beca',
            options={'verbose_name': 'Beca', 'verbose_name_plural': 'Becas'},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterField(
            model_name='beca',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beca',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='becas.institucion'),
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=145)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('imagen', models.ImageField(upload_to='becas')),
                ('file', models.FileField(upload_to='becas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('beca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatorias', to='becas.beca')),
            ],
        ),
    ]
