# Generated by Django 3.2 on 2023-03-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becas', '0002_auto_20230316_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'verbose_name': 'Convocatoria', 'verbose_name_plural': 'Convocatorias'},
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
