# Generated by Django 3.2 on 2023-03-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becas', '0003_auto_20230316_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='file',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='imagen',
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='archivo_convocatoria',
            field=models.FileField(blank=True, null=True, upload_to='becas', verbose_name='Archivo de la convocatoria'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='archivo_resultado',
            field=models.FileField(blank=True, null=True, upload_to='becas', verbose_name='Archivo de los resultados'),
        ),
    ]
