# Generated by Django 3.2 on 2023-03-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('becas', '0004_auto_20230317_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='archivo_convocatoria',
            field=models.FileField(upload_to='becas', verbose_name='Archivo de la convocatoria'),
        ),
    ]
