# Generated by Django 3.2 on 2023-02-09 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='usuario',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='articuloimagen',
            name='articulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='noticias.articulo'),
        ),
    ]
