# Generated by Django 3.2 on 2024-02-26 22:53

from django.db import migrations, models
import sgc.models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=sgc.models.documento_upload_to),
        ),
    ]
