# Generated by Django 3.2 on 2024-02-26 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0002_alter_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='revision',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
