# Generated by Django 3.2 on 2024-02-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0003_auto_20240226_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
