# Generated by Django 3.2 on 2024-02-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa_trabajo_uts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='bolsa_trabajo_uts')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Formato Referencia',
                'verbose_name_plural': 'Formatos Referencias',
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='descripcion',
            options={'verbose_name': 'Descripción', 'verbose_name_plural': 'Descripciones'},
        ),
        migrations.AlterModelOptions(
            name='vacante',
            options={'verbose_name': 'Vacante', 'verbose_name_plural': 'Vacantes'},
        ),
    ]
