# Generated by Django 3.2 on 2024-02-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa_trabajo_uts', '0003_vacante_formato_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacante',
            name='formato_referencia',
        ),
    ]
