# Generated by Django 3.2 on 2024-02-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa_trabajo_uts', '0004_remove_vacante_formato_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='formato_referencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='bolsa_trabajo_uts.formatoreferencia'),
            preserve_default=False,
        ),
    ]
